FLAGS = -std=c++11 -pedantic-errors 
testmain: testmain.o thingsClasses.o map.o camera.o
	g++ $(FLAGS) $^ -o $@
testmain.o: testmain.cpp
	g++ $(FLAGS) -c $<
thingsClasses.o: thingsClasses.cpp thingsClasses.h
	g++ $(FLAGS) -c $<
map.o: map.cpp map.h
	g++ $(FLAGS) -c $<
camera.o: camera.cpp camera.h
	g++ $(FLAGS) -c $<
